title: Sw33tBit
description: Tech blog
author: BitR13x
avatar: /logo.png
email: sw33tbit@protonmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
skin: midnight

# Uncomment the below line and set the tracking ID for enabling Google Analytics
#
# google_analytics:

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
#
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - gen.py

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: bitr13x
  card: summary
logo: logo.png
social:
  name: BitR13x
  links:
    - https://twitter.com/bitr13x
    - https://github.com/bitr13x
google_site_verification: #None
lang: en
